# Generated by Django 5.1.7 on 2025-03-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_actividad_estado_delete_estadoactividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariocronograma',
            name='cronograma',
        ),
        migrations.RemoveField(
            model_name='fechassiembra',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.RemoveField(
            model_name='usuariocronograma',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Cronograma',
        ),
        migrations.DeleteModel(
            name='FechasSiembra',
        ),
        migrations.DeleteModel(
            name='UsuarioCronograma',
        ),
    ]
